The `MyList` test module
==========================

Using `print_sorted`
----------------

>>> MyList = __import__('1-my_list').MyList

Correct tests:

>>> my_list = MyList()
>>> my_list.append(1)
>>> my_list.append(4)
>>> my_list.append(2)
>>> my_list.append(3)
>>> my_list.append(5)
>>> my_list.print_sorted()
[1, 2, 3, 4, 5]
>>> my_list
[1, 4, 2, 3, 5]

>>> my_list = MyList()
>>> my_list.print_sorted()
[]

>>> my_list = MyList()
>>> my_list.append((2, 6))
>>> my_list.append((8, 5))
>>> my_list.append((36, 65))
>>> my_list.append((-12, 45))
>>> my_list.append((72, -200))
>>> my_list.print_sorted()
[(-12, 45), (2, 6), (8, 5), (36, 65), (72, -200)]

>>> my_list = MyList()
>>> my_list.append((2.5, 6))
>>> my_list.append((8.6, 5))
>>> my_list.append((36.3, 65))
>>> my_list.append((-12, 45))
>>> my_list.append((72, -200))
>>> my_list.print_sorted()
[(-12, 45), (2.5, 6), (8.6, 5), (36.3, 65), (72, -200)]

>>> my_list = MyList([1, 2, -1])
>>> my_list.print_sorted()
[-1, 1, 2]

>>> my_list = MyList([5])
>>> my_list.print_sorted()
[5]

>>> my_list = MyList([5, 3, 8])
>>> my_list += [3]
>>> my_list.print_sorted()
[3, 3, 5, 8]

Incorrect tests

>>> my_list = MyList([1, 'Stop patriarchy', -1])
>>> my_list.print_sorted()
Traceback (most recent call last):
TypeError: '<' not supported between instances of 'str' and 'int'

>>> my_list = MyList(None)
Traceback (most recent call last):
TypeError: 'NoneType' object is not iterable

>>> my_list = MyList([5, 1],[3, 9])
Traceback (most recent call last):
TypeError: list expected at most 1 argument, got 2

>>> my_list = MyList([5],[3])
Traceback (most recent call last):
TypeError: list expected at most 1 argument, got 2

>>> my_list = MyList([5, 3, 8])
>>> my_unknown_list.print_sorted()
Traceback (most recent call last):
NameError: name 'my_unknown_list' is not defined
